name: 'Terraform - Dev'

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

env:
  TF_ENV: dev
  TF_TEST_DIR: ./tf/environments/dev
  TF_VAR_FILE: ./tf/environments/dev/terraform.tfvars

jobs:
  # Scan repository for secrets using Gitleaks
  secrets-scan:
    name: 'Secrets Scan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Gitleaks # Detect hardcoded secrets in all files, including Terraform
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--source=. --verbose"

  # Run Checkov for static code analysis of Terraform files
  checkov:
    name: 'Checkov Scan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov # Static analysis for Terraform security and compliance
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./tf/environments/dev

  # Run TFSec for static analysis of Terraform files
  tfsec:
    name: 'TFSec Scan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run TFSec # Security scanner for Terraform code
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./tf/environments/dev

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: [checkov, tfsec, secrets-scan]
    environment:
      name: dev

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      # Set up the Azure credentials for authentication
      - name: Login to Azure # Authenticate to Azure for Terraform
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Terraform Init # Initialize Terraform working directory
        run: terraform init -var-file="${{ env.TF_VAR_FILE }}"
        working-directory: ${{ env.TF_TEST_DIR }}
      - name: Terraform Validate # Validate Terraform configuration
        run: terraform validate -no-color -var-file="${{ env.TF_VAR_FILE }}"
        working-directory: ${{ env.TF_TEST_DIR }}
      - name: Terraform Plan # Generate Terraform execution plan
        run: terraform plan -input=false -var-file="${{ env.TF_VAR_FILE }}"
        working-directory: ${{ env.TF_TEST_DIR }}
      # Only apply when this workflow is triggered by a push to the dev branch (i.e., after merge)
      - name: Terraform Apply # Apply Terraform changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        run: terraform apply -auto-approve -input=false -var-file="${{ env.TF_VAR_FILE }}"
        working-directory: ${{ env.TF_TEST_DIR }}

  terratest:
    name: 'Terratest'
    runs-on: ubuntu-latest
    needs: terraform
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure # Authenticate to Azure for Terratest
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Set up Go # Install Go for running Terratest
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies # Install Go dependencies for tests
        run: go mod tidy
        working-directory: ./test

      - name: Run Terratest # Dry-run (plan) targeted at dev environment
        env:
          TF_TEST_DIR: ${{ env.TF_TEST_DIR }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: go test -v ./...
        working-directory: ./test

  pr-review:
    name: 'Automate PR Review'
    runs-on: ubuntu-latest
    needs: [terraform]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add PR Review Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "Automated review: All checks have passed and this PR is ready for further review or merge."
      - name: Add PR Review Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "Automated review: All checks have passed and this PR is ready for further review or merge."
