name: 'Terraform - Other Branches'

on:
  push:
    branches-ignore: [ "main", "dev", "qa" ]
  pull_request:
    branches-ignore: [ "main", "dev", "qa" ]

permissions:
  contents: read

jobs:
  secrets-scan:
    name: 'Secrets Scan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--source=. --verbose"

  checkov:
    name: 'Checkov Scan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./tf/environments/sandbox # or a default path

  tfsec:
    name: 'TFSec Scan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./tf/environments/sandbox # or a default path

  terratest:
    name: 'Terratest'
    runs-on: ubuntu-latest
    needs: [checkov, tfsec]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod tidy
        working-directory: ./test
      - name: Run Terratest
        run: go test -v ./...
        working-directory: ./test
